spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/blog
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: info